name: Node.js CI
on:
    push:
        branches:
            - main
    schedule:
            -  cron: "30 14 01 * *"
jobs:
    build:
        runs-on: ubuntu-20.04
        timeout-minutes: 180
        steps:
            -   uses: actions/checkout@v3
            -   name: "build dependencies 1"
                run: pwd && bash tools/install-build-deps-01.sh
            -   name: "build dependencies 2"
                run: bash tools/install-build-deps-02.sh
            -   name: 'create index.html'
                run: bash tools/setup-gh-pages-step-01-index.sh
            -   name: 'create chromium extension release archive '
                run: bash tools/setup-gh-pages-step-02-chromium-extension.sh
            -   name: 'Deploy GitHub Pages'
                uses: peaceiris/actions-gh-pages@v3
                with:
                    deploy_key: ${{ secrets.ACTION_DEPLOY_KEY }}
                    publish_dir: gh-pages
                    publish_branch: gh-pages
                    allow_empty_commit: true
                    enable_jekyll: false
                    keep_files: true
