name: Node CI
on:
  push:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        cat /etc/os-release
        echo $(id -u)
        echo $(id -g)
        npm install -d
        npm run build --if-present
        npm install gitbook-cli -g
        sh gitbook-build.sh
        cp -r docs/docs public/docs
        cp index.html public/
      env:
        CI: true
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        CI: true
        ACCESS_TOKEN: ${{ secrets.github_io }}
        BRANCH: gh-pages
        FOLDER: public
        BUILD_SCRIPT: |
          cp index.html ../
          pwd
          echo "ok"


